[package]
authors = ["Jonas Nicklas <jonas.nicklas@gmail.com>"]
name = "graphers"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
lalrpop = "0.11.0"

[dependencies]
lalrpop-util = "0.11.0"
