[package]
name = "graphers"
version = "0.1.0"
authors = ["Jonas Nicklas <jonas.nicklas@gmail.com>"]

[dependencies]
graphers_core = { path = "./graphers_core" }
graphers_parse = { path = "./graphers_parse" }
